### ISSUE TITLE
Require from command line via -r/--require

### ISSUE THREAD

**Issue by mniehe** [keithmorris/node-dotenv-extended#1]
Would be nice to be able to require this package from the command line. An example of how dotenv does it:
```
node -r dotenv/config app.js
```

The file that allows this can be found [https://github.com/motdotla/dotenv/blob/master/config.js](https://github.com/motdotla/dotenv/blob/master/config.js).

**Comment by keithmorris** [comment]
@mniehe, good suggestion. I just added that feature and will be releasing shortly.

**Comment by keithmorris** [comment]
Release of v1.0.1 adds this feature.

**Comment by mniehe** [comment]
Awesome, thanks!
