### ISSUE TITLE
feature request/idea: .env.schema regexes

### ISSUE THREAD

**Issue by mmkal** [keithmorris/node-dotenv-extended#10]
What do you think about `.env.schema` supporting regular expressions? e.g.

```bash
# username can't contain spaces
DB_USERNAME=^\S+$

#password must be between 8 and 40 characters
DB_PASSWORD=^.{8,40}$

# only postgres and sqllite databases are supported
DB_DIALECT=(postgres|sqllite)
```

etc.

**Comment by keithmorris** [comment]
@mmkal I'd be interested to see a pull request for this. Please keep backward compatibility in mind as you develop the feature.

**Comment by mmkal** [comment]
Looks like this is done 👍
