### ISSUE TITLE
cli not honoring already defined env vars

### ISSUE THREAD

**Issue by vlindhol** [keithmorris/node-dotenv-extended#23]
Using `dotenv-extended` as a CLI tool works fine if the wanted env var is found in `.env.defaults` or `.env`, but if we are passing in the env variable from elsewhere (in my case as args to a Docker container) the value is not captured.

To reproduce:
```
cat > dotenv-test.sh <<END
#!/bin/sh

echo "In script:" $DOTENV_TEST
END
```
and

```
echo "DOTENV_TEST=default" >> .env.defaults
echo "DOTENV_TEST=nondefault" >> .env

npm install dotenv-extended
DOTENV_TEST=commandline npx dotenv-extended dotenv-test.sh
```

* Wanted output: `In script: commandline`
* Got output: `In script: nondefault`

I originally used an npm script, not `npx`, but same thing there. Using dotenv-extended 2.0.2. Is there something I've misunderstood about this functionality?

**Comment by vlindhol** [comment]
Some more findings: I made a JS version of the shell script above, which actually imports `dotenv-extended`, and put it in an npm script. Running `npm run dotenv-test-js` produces the correct output (`nondefault`) and `DOTENV_TEST=commandline npm run dotenv-test-js` also produces the correct output (`commandline`).

So it looks like the way the CLI version loads the shell script is at fault.

**Comment by keithmorris** [comment]
@vlindhol Thanks for finding this. I'll take a look as soon as I'm able to see if I can figure it out. Feel free to take a look yourself and submit a Pull Request

**Comment by vlindhol** [comment]
@keithmorris PR submitted a while ago, in case you missed it!
