### ISSUE TITLE
Add "import" syntax to README

### ISSUE THREAD

**Issue by joelparkerhenderson** [keithmorris/node-dotenv-extended#25]
What is the recommended way to use this with the newer "import" syntax, rather than the older "require" syntax? 

What is a good way to add this info to the README?

**Comment by joelparkerhenderson** [comment]
This is still an open question - is there an answer and/or change coming?

**Comment by niftylettuce** [comment]
You can use `require` syntax in `import` projects.  But you could just `import dotEnvExtended from 'dotenv-extended';` and then `dotEnvExtended.load();` after.  There's really nothing different.  We don't have specific exports or anything that differ or have some weird exports.defaults nonsense.

**Comment by keithmorris** [comment]
@joelparkerhenderson There are explicit exports for `parse`, `config`, and `load`. The default export exports and object that has all three methods:

`export default {parse, config, load};`

So you should be able to use it exactly like @niftylettuce mentioned above.

**Comment by joelparkerhenderson** [comment]
Good thank you both! I'll do a pull request now.

The project that I was using didn't allow the "require" syntax. And I see in retrospect that the text "dotenv-extended" was being converted to "dotenvExtended" (with "env" as lower case) rather than "dotEnvExtended" (with "Env" as title case). For example the popular node package "dotenv" uses title case "Dotenv" rather than "DotEnv". So thank you both for the info and also for explaining how I could find the help in the source. Kudos!
