### ISSUE TITLE
Export default please

### ISSUE THREAD

**Issue by niftylettuce** [keithmorris/node-dotenv-extended#3]
Hello - can you please export a default object containing `{ load, config, ... }`?  Right now in ES6 I have to do `import { load } from dotenv-extended` which isn't so user-friendly.  If you could just add a default export that'd be great!

**Comment by niftylettuce** [comment]
This is for usage with my package here <https://github.com/niftylettuce/dotenv-parse-variables>

**Comment by keithmorris** [comment]
@niftylettuce Let me know if this works for you or if you run into any problems.

**Comment by niftylettuce** [comment]
tyvm @keithmorris
