### ISSUE TITLE
Configure via environment

### ISSUE THREAD

**Issue by Levino** [keithmorris/node-dotenv-extended#34]
I am doing something like this:
```bash
DOTENV_CONFIG_PATH='.env.development' node -r dotenv-extended/config ./start.js
```
but I would like to get an error when I forget a variable in the `.env.development` file. So what I would actually want to run is:
```bash
DOTENV_CONFIG_ERROR_ON_MISSING=true DOTENV_CONFIG_PATH='.env.development' node -r dotenv-extended/config ./start.js
```
and then have errors thrown when `.env.development` is incomplete.

As it looks one cannot configure the additional opitions of `dotenv-extended` via environment variables like it is the case for `dotenv`.

**Comment by keithmorris** [comment]
Hi @Levino 

The library doesn't currently support setting dotenv-extended configurations via environment variables. However, you should be able to do this with the following:
`node -r dotenv-extended/config ./start.js dotenv_config_path=.env.development dotenv_config_errorOnMissing=true`

Check out the section from the readme here: https://github.com/keithmorris/node-dotenv-extended#load-configs-from-command-line

**Comment by keithmorris** [comment]
Also, just looking into this, it should be pretty easy to add support for using environment variables like DOTENV_CONFIG_PATH, DOTENV_CONFIG_ERROR_ON_MISSING. I'll look into adding this to the 3.0.0 release which is already a pending pull request.

**Comment by keithmorris** [comment]
Added in 2.8.0 on 2020.03.25. Thanks @Levino
