### ISSUE TITLE
Feature request: Override

### ISSUE THREAD

**Issue by basickarl** [keithmorris/node-dotenv-extended#35]
Hi, I'd like to request a feature if possible.

I'd like an override field setting. I would like process.env to override the .env values if they are set. Right now I have to do this manually, or have I missed something?

**Comment by keithmorris** [comment]
Hi @basickarl. You should be able to do this by setting the `includeProcessEnv` to true like the following:

```javascript
require('dotenv-extended').load({
    includeProcessEnv: false,
});
```
By doing this, this will load all of the values from your `.env` and `.env.defaults` files and then overrides them with anything in the `process.env` file. Note this this will include *all* values in process.env into your loaded config. Also, this does not work if you have `overrideProcessEnv` set to `true`. Those two settings pretty much exclude each other

Let me know if this doesn't work for you.
