### ISSUE TITLE
Optional schema keys?

### ISSUE THREAD

**Issue by spacesuitdiver** [keithmorris/node-dotenv-extended#41]
Is it possible to have optional values in schema?

**Comment by FokkeZB** [comment]
Unfortunately not as the regex will fail if a value is `undefined`. I just ran into that and I'll open a PR.

**Comment by FokkeZB** [comment]
@keithmorris I think this can be closed now #45 has been published.

**Comment by keithmorris** [comment]
This has been fixed as of release v2.9.0
