### ISSUE TITLE
Regex seems like it should be more strict?

### ISSUE THREAD

**Issue by spacesuitdiver** [keithmorris/node-dotenv-extended#42]
I'm no regex wizard but I can't seem to figure out how to properly validate for a simple app identifier.

At a most basic level I would like for any permutation of dots and [a-zA-Z0-9] to pass but any other character used to fail.

PASS:
com
com.mycorp.we
com.mycorp.we.feature
com.mycorp.we.feature.prd

FAIL:
c-
com.my-corp
com-my-corp

I'd honestly expect `[a-zA-Z0-9]` as is to work but all of the failure cases with this regex pass.

**Comment by FokkeZB** [comment]
The FAIL cases pass because they **do** _contain_ `[a-zA-Z0-9]`.

What you're looking for is `^[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*$`
