### ISSUE TITLE
Ship binary for use from cli?

### ISSUE THREAD

**Issue by mmkal** [keithmorris/node-dotenv-extended#7]
Hi,

First, thanks very much for the package, it's great. I would love it if I could expand its use further though.

For example, in my project I have some environment variables set up for connecting to a database. But right now they're duplicated between .env.defaults and docker-compose.yml. If this package shipped with a binary (similar to [cross-env](https://github.com/kentcdodds/cross-env/blob/master/src/bin/cross-env.js)) I could solve this problem (as well as the general problem of passing the same environment variables to non-node applications) by updating
docker-compose foo
to
dotenv-extended docker-compose foo

And then using ${MY_ENVIRONMENT_VARIABLE} inside docker-compose.yml (which can read from environment variables but doesn't have the same defaults logic as dotenv-extended). 

Would this be something you'd be open to?

**Comment by keithmorris** [comment]
@mmkal I think this is an interesting idea and shouldn't be too difficult to do. Feel free to submit a pull request or I'll see if I can get some time this week to knock it out.

**Comment by keithmorris** [comment]
@mmkal I had some extra time today so I went ahead and coded out the feature and released a new version as 2.0.0. I have not thoroughly tested this on Windows but it seems to work pretty well on *nix environments. Let me know if you have any suggestions.

**Comment by mmkal** [comment]
It works great - thanks!
